source 'https://rubygems.org'

ruby '2.1.6'

gem 'byebug'
gem 'clockwork'
gem 'dalli'
gem 'espn_scraper', github: 'mikesilvis/espn-scraper'
gem 'puma'
gem 'rack'
gem 'sidekiq'
gem 'sinatra'
gem 'pusher'
gem 'faraday'
gem 'newrelic_rpm'
